<?php
/**
 * WofhTools
 *
 * @author      delphinpro <delphinpro@gmail.com>
 * @copyright   copyright © 2019 delphinpro
 * @license     licensed under the MIT license
 */

define('DIR_ROOT', realpath(__DIR__.'/../../'));
define('DIR_CACHE', DIR_ROOT.DIRECTORY_SEPARATOR.'.cache');
define('DIR_LOGS', DIR_ROOT.DIRECTORY_SEPARATOR.'.logs');
define('DIR_TMP', DIR_ROOT.DIRECTORY_SEPARATOR.'.tmp');
define('DIR_CONFIG', DIR_ROOT.DIRECTORY_SEPARATOR.'config');
define('DIR_TWIG_TEMPLATES', DIR_ROOT.DIRECTORY_SEPARATOR.'private'.DIRECTORY_SEPARATOR.'templates');

define('STD_DATETIME', 'Y-m-d H:i:s');
define('STD_DATE_H', 'Y-m-d__H-00-00');
define('DATE_FILE', 'Y-m-d_H');

//const EVENT_TOWN_CREATE = 100;
//const EVENT_TOWN_RENAME = 101;
//const EVENT_TOWN_LOST = 102;
////const EVENT_TOWN_DESTROY = 103;
//
//const EVENT_ACCOUNT_CREATE = 200;
//const EVENT_ACCOUNT_COUNTRY_IN = 201;
//const EVENT_ACCOUNT_COUNTRY_OUT = 202;
//const EVENT_ACCOUNT_COUNTRY_CHANGE = 203;
//const EVENT_ACCOUNT_DELETE = 204;
//const EVENT_ACCOUNT_RENAME = 205;
//const EVENT_ACCOUNT_ROLE_IN = 206;
//const EVENT_ACCOUNT_ROLE_OUT = 207;
//
//const EVENT_COUNTRY_CREATE = 300;
//const EVENT_COUNTRY_FLAG = 301;
//const EVENT_COUNTRY_RENAME = 302;
//const EVENT_COUNTRY_DESTROY = 303;
//const EVENT_COUNTRY_PEACE = 304;
//const EVENT_COUNTRY_WAR = 305;
//
//const EVENT_WONDER_DESTROY = 400;
//const EVENT_WONDER_CREATE = 401;
//const EVENT_WONDER_ACTIVATE = 402;

const EVENT_TOWN_CREATE = 'TOWN_CREATE';
const EVENT_TOWN_RENAME = 'TOWN_RENAME';
const EVENT_TOWN_LOST = 'TOWN_LOST';

const EVENT_ACCOUNT_CREATE = 'ACCOUNT_CREATE';
const EVENT_ACCOUNT_COUNTRY_IN = 'ACCOUNT_COUNTRY_IN';
const EVENT_ACCOUNT_COUNTRY_OUT = 'ACCOUNT_COUNTRY_OUT';
const EVENT_ACCOUNT_COUNTRY_CHANGE = 'ACCOUNT_COUNTRY_CHANGE';
const EVENT_ACCOUNT_DELETE = 'ACCOUNT_DELETE';
const EVENT_ACCOUNT_RENAME = 'ACCOUNT_RENAME';
const EVENT_ACCOUNT_ROLE_IN = 'ACCOUNT_ROLE_IN';
const EVENT_ACCOUNT_ROLE_OUT = 'ACCOUNT_ROLE_OUT';
const EVENT_ACCOUNT_RATING_HIDE = 'ACCOUNT_RATING_HIDE';
const EVENT_ACCOUNT_RATING_SHOW = 'ACCOUNT_RATING_SHOW';

const EVENT_COUNTRY_CREATE = 'COUNTRY_CREATE';
const EVENT_COUNTRY_FLAG = 'COUNTRY_FLAG';
const EVENT_COUNTRY_RENAME = 'COUNTRY_RENAME';
const EVENT_COUNTRY_DESTROY = 'COUNTRY_DESTROY';
const EVENT_COUNTRY_PEACE = 'COUNTRY_PEACE';
const EVENT_COUNTRY_WAR = 'COUNTRY_WAR';

const EVENT_WONDER_DESTROY = 'WONDER_DESTROY';
const EVENT_WONDER_CREATE = 'WONDER_CREATE';
const EVENT_WONDER_ACTIVATE = 'WONDER_ACTIVATE';
